# .sops.yaml
---
creation_rules:
  # ssh private key files starting with id_
  - path_regex: ssh/dot-ssh/id_[A-Za-z0-9_ -]*$
    age: age1v3fks8crfh4a8m5tszhdr977ckzedg9ak3f6hhwtjkmr58665fgsqs080u
  # Fallback
  # - age: age1v3fks8crfh4a8m5tszhdr977ckzedg9ak3f6hhwtjkmr58665fgsqs080u
